### PR TITLE
Create module to release a kt1.1 artifact

### PR DESCRIPTION
**Pull request by nhaarman**
This should generate another artifact that includes the `1.1.x` version of Kotlin, and fix issues like #156, #162 and #163.

### CODE REVIEW

**Comment by sdeleuze** [comment]
@nhaarman Why not just avoiding to expose `kotlin-stdlib` and `kotlin-reflect` dependencies in the Maven dependencies by using a scope like `compileOnly` and `compileTestOnly`,

That would avoid creating specific artifact for Kotlin 1.1, 1.2, 1.3 ...

**Comment by nhaarman** [comment]
While the `stdlib` will probably always be included by the client, `reflect` might not.

**Comment by sdeleuze** [comment]
I agree and I don't say the approach I propose is perfect but I think this is the one adapted by very well known project like Jackson Kotlin and I am really not a fan of seeing a project that propose `mockito-kotlin-kt1.1`, `mockito-kotlin-kt1.2` and `mockito-kotlin-kt1.3` artifact in less than a year.

I will ask on Kotlin Slack if somebody has a better solution to this issue.

**Comment by sdeleuze** [comment]
I have created https://youtrack.jetbrains.com/issue/KT-18398 to try to find a better outcome than Kotlin version specific artifacts.

**Pull request merged**
