### PR TITLE
Add explicit capture with default value

### PR DESCRIPTION
**Pull request by neworld**
This PR will help for people like me, who have tons of final classes without an empty constructor. 

Also, it could solve #20

### CODE REVIEW

**Comment by nhaarman** [comment]
Thank you for your input!
What do you think of #23 to solve this issue instead?

**Comment by neworld** [comment]
#23 will fix this issue. But in my friendly opinion, it is not clean. The statics in tests adds complexity and  race-conditions. The problem is solved by registering instance creator in every class:
```
    @Test
    fun registerCreatorWithMock() {
        val constructorWithObject = ConstructorWithObject(mock())
        MockitoKotlin.registerInstanceCreator { constructorWithObject }
        val lambda: Function1<ConstructorWithObject, Unit> = mock()

        verify(lambda).invoke(any())
    }
```

But this adds more boilerplate. Also, the second example will fail, because you can't use mock() during verification:

```
    @Test
    fun registerCreatorWithMock() {
        MockitoKotlin.registerInstanceCreator { ConstructorWithObject(mock()) }
        val lambda: Function1<ConstructorWithObject, Unit> = mock()
        
        verify(lambda).invoke(any())
    }
```

**Comment by nhaarman** [comment]
Good point.

**Comment by neworld** [comment]
Because of global state. Since I don't know how to ensure initialize static before all tests, there are chances somebody will forget to init them, but tests still pass. Adding new tests, removing, altering them can change the order of tests and break that particular test.

**Comment by neworld** [comment]
I realized this PR fixes a symptom, not [the real issue](https://github.com/nhaarman/mockito-kotlin/issues/24). #23 could work as a temporal solution. So, I close this PR.

**Pull request closed without merging**
