### PR TITLE
Better spy support + argumentCaptor + tests

### PR DESCRIPTION
**Pull request by angryziber**
Making a pull request against dev branch, as you requested

### CODE REVIEW

**Comment by nhaarman** [comment]
Great stuff!

**Comment by angryziber** [comment]
Thanks for merging! Do you have plans to make a release soon?

**Comment by nhaarman** [comment]
I'm looking into adding more of the Mockito API to the library for easy usage. Expect something in the next couple of days.

**Comment by cbxp** [comment]
Any news on the release? :-)

**Comment by henrikpersson** [comment]
Would love a release with the argumentCaptor!

**Comment by nhaarman** [comment]
Sorry it took a while guys, `0.3.0` has just been released.

**Pull request merged**
