### PR TITLE
Use nulls not instances

### PR DESCRIPTION
**Pull request by Sarah-Gallitz**
This successfully satisfies the mockito library but greatly simplifies the code. Instance creators are no longer needed.

Thank you for submitting a pull request! But first:

- [x]  Can you back your code up with tests?
- [x]  Keep your commits clean: squash your commits if necessary.
- [x]  Make sure you're targeting the dev branch with the PR.

### CODE REVIEW

**Comment by nhaarman** [comment]
IIRC I have read somewhere that this is undocumented behavior and subject to change.
Though this would really make life a lot easier, I am not entirely sure if we can depend on this.

I will look into it.

**Comment by nhaarman** [comment]
See https://youtrack.jetbrains.com/issue/KT-8135.

**Comment by Sarah-Gallitz** [comment]
Fair enough. It seems they acknowledge something like this is necessary for testing, but that was in 2015. 
Should I close the PR until an official stance is taken?

**Comment by nhaarman** [comment]
Let's close this for now, the `mock-maker-inline` feature eases things as well.

**Pull request closed without merging**
